FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app


# Copy the script and any necessary files to the container
COPY . .

# Set the default command to execute the script
CMD ["python", "S1_process_files.py"]

